# Generated by Django 4.0.4 on 2022-05-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petr', '0002_alter_art_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Arts/<django.db.models.fields.CharField>gallery/img/%Y/%m/%d/', verbose_name='Image'),
        ),
    ]
