# Generated by Django 4.0.3 on 2022-06-06 14:36

import GHome.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_creation', models.DateField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('cover', models.ImageField(upload_to=GHome.models.attachment_path_album)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('date_of_creation', models.DateField(default=django.utils.timezone.now)),
                ('text', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to=GHome.models.attachment_path_author)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a film genre (e.g. sci-fi, comedy)', max_length=50, unique=True, verbose_name='Genre name')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('date_of_addition', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, choices=[('Img', 'Image'), ('Gif', 'Gif'), ('Video', 'video')], max_length=5)),
                ('file', models.FileField(upload_to=GHome.models.attachment_path_attachment)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHome.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='GHome.author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GHome.author'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(help_text='Select a genre for this Album', to='GHome.genre'),
        ),
    ]
