# Generated by Django 4.0.3 on 2022-06-06 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
